# https://fedoramagazine.org/using-ansible-setup-workstation/
- hosts: localhost
  tasks:
    - name: Remove GNOME Bloat
      become: yes
      package:
        name: 
          - gnome-maps
          - gnome-boxes
          - gnome-weather
          - cheese
        state: absent
    - name: Remove Rhythmbox
      become: yes
      package:
        name: rhythmbox
        state: absent
    - name: Install Gimp and Inkscape
      become: yes
      package:
        name: 
          - gimp
          - inkscape
        state: present
    - name: Install qBittorrent
      become: yes
      package:
        name: qbittorrent
        state: present
    - name: Install extra packages
      become: yes
      package:
        name:
          - inotify-tools
          - neovim
          - neovim-qt
          - neofetch
          - fuse-encfs
          - duperemove
          - fdupes
          - qt5-designer
          - evemu
          - sqlite
          - libreoffice-draw
          - net-tools
          - vim-enhanced
          - pv 
          - iotop-c
          - adb
          - gnome-sudoku
          - python3-ipython
          - xeyes
          - stress-ng
          - scrcpy
        state: present
    - name: Install multimedia
      become: yes
      package:
        name:
          - mplayer
          - vlc
          - qiv
          - unrar
          - p7zip
          - obs-studio
        state: present
    - name: Install python-psutil
      become: yes
      package:
        name: python-psutil
        state: present
    - name: Set allow volume above 100%
      dconf: key="/org/gnome/desktop/sound/allow-volume-above-100-percent" value=true
