---
- name: Install Gimp and Inkscape
  become: yes
  package:
    name:
      - gimp
      - inkscape
    state: present

- name: Install LaTeX
  become: yes
  package:
    name:
      - texlive-scheme-medium
      - texlive-inconsolata
      - texlive-tkz-euclide
      - texlive-tikz-3dplot
      - texlive-tikzmark
      - texlive-tikz-cd
      - texlive-tikz-dimline
      - texlive-tikzsymbols
      - texlive-tikz-among-us
      - texlive-tikzducks
      - texlive-tikzposter
      - texlive-contour
      - texlive-pgfornament
      - texlive-qrcode
      - texlive-augie
      - drawing
    state: present

- name: Install neovim
  become: yes
  package:
    name:
      - neovim
      - python3-neovim
    state: present

- name: Install python packages
  become: yes
  package:
    name:
      - python3-ipython
      - python3-scipy
      - python3-sympy
      - python3-toml
      - python3-matplotlib
      - python3-opencv
      - sqlite
      - xeyes
    state: present

- name: Install pt_BR language support
  become: yes
  package:
    name:
      - langpacks-pt_BR
      - libreoffice-langpack-pt-BR
      - libreoffice-help-pt-BR
    state: present

- name: Install toolbox
  become: yes
  package:
    name: toolbox
    state: present

- name: Install extra packages
  become: yes
  package:
    name:
      - openssl
      - zstd
      - smartmontools
      - gstreamer1-plugin-openh264
      - fira-code-fonts
      - secrets
      - xournal
      - qrencode
      - gcc-c++
      - neofetch
      - fuse-encfs
      - duperemove
      - fdupes
      - net-tools
      - pv
      - iotop-c
      - adb
      - levien-inconsolata-fonts
      - glib2-devel
      - aria2c
      - libwebp-tools
    state: present
