---
- name: Install packages
  become: yes
  package:
    name:
      - gimp
      - drawing
      - texlive-scheme-medium
      - texlive-inconsolata
      # - texlive-tkz-euclide
      # - texlive-tikz-3dplot
      - texlive-tikzmark
      # - texlive-tikz-cd
      - texlive-tikz-dimline
      - texlive-tikzsymbols
      # - texlive-tikz-among-us
      # - texlive-tikzducks
      # - texlive-tikzposter
      # - texlive-circuitikz
      # - texlive-contour
      # - texlive-pgfornament
      - texlive-qrcode
      - texlive-augie
      - texlive-tikzfill
      - texlive-listingsutf8
      - libwebp-tools
      - pandoc
      - neovim
      - levien-inconsolata-fonts
      - python3-neovim
      - python3-ipython
      - python3-numpy
      - python3-scipy
      - python3-sympy
      - python3-matplotlib
      - python3-opencv
      - sqlite
      - xeyes
      - langpacks-pt_BR
      - libreoffice-langpack-pt-BR
      - libreoffice-help-pt-BR
      - openssl
      - zstd
      - smartmontools
      - fira-code-fonts
      - secrets
      - xournal
      - qrencode
      - gcc-c++
      - clang-tools-extra
      - clang
      - neofetch
      - fuse-encfs
      - duperemove
      - fdupes
      # - net-tools
      - pv
      - iotop-c
      - adb
      - aria2
      - libwebp-tools
      - fio
      - gnome-sudoku
      - p7zip
      - unrar
      - aria2c
      - ffmpeg-free
      - obs-studio
      - qiv
    state: present
