---
- block:
  - name: Check for RPM Fusion Free repo
    stat: path=/etc/yum.repos.d/rpmfusion-free.repo
    register: rpmfusion_free_installed

  - name: Check for RPM Fusion Nonfree repo
    stat: path=/etc/yum.repos.d/rpmfusion-nonfree.repo
    register: rpmfusion_nonfree_installed

  - name: Check for Copr repo for scrcpy
    stat: path="/etc/yum.repos.d/_copr:copr.fedorainfracloud.org:zeno:scrcpy.repo"
    register: copr_scrcpy_installed
